package cn.sinjinsong.pay.dao;

import cn.sinjinsong.pay.domain.entity.PayDO;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface PayDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbggenerated
     */
    int insert(PayDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbggenerated
     */
    int insertSelective(PayDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbggenerated
     */
    PayDO selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PayDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PayDO record);
}