package cn.sinjinsong.skeleton.domain.entity.mail;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer;
import com.fasterxml.jackson.datatype.jsr310.ser.LocalDateTimeSerializer;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class MailTextDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_text.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_text.send_time
     *
     * @mbggenerated
     */
    private LocalDateTime sendTime;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_text.mail_text
     *
     * @mbggenerated
     */
    private String mailText;

}